import math

FPS = 60
TILESIZE = 30
ROWS = 15
COLS = 15
WIDTH = COLS * TILESIZE
HEIGHT = ROWS * TILESIZE
SIZE = (WIDTH*2, HEIGHT)

FOV = 60 * (math.pi / 180)
RESULUTION = 10
NUM_RAYS = int((WIDTH/3) // RESULUTION)

OFFSET = WIDTH