import math

FPS = 60
RESULUTION = 1
WIDTH = 160*RESULUTION
HEIGHT = 120*RESULUTION
W2 = WIDTH/2
H2 = HEIGHT/2
PIXEL_SCALE = int(4//RESULUTION)
SIZE = (WIDTH*PIXEL_SCALE, HEIGHT*PIXEL_SCALE)

MAP_LOAD = "./3d_rendering/map.json"

# NUM_SECTORS = 4
# NUM_WALLS = 16